# Change these first
owner: CircuitVerse # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Main Platform
    url: https://circuitverse.org/
  - name: Interactive Book
    url: https://learn.circuitverse.org/
  - name: Docs
    url: https://docs.circuitverse.org/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.circuitverse.org
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/42944450?s=200&v=4
  name: CircuitVerse System Status
  introTitle: ""
  introMessage: If you face any issues, reach out to us on [slack](http://circuitverse.org/slack) or [email](mailto:support@circuitverse.org).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
